=begin
==========================================================================
Bookmark Parser -
Parses a bookmark.html file generated by a browser (currently tested in
Firefox, Chrome and Safari) and return a hash with each title and url.

Copyright (C) 2012  Jorge Rodríguez

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
==========================================================================
=end
class BookmarkParser

=begin
self.parseFile - Processes a HTML file with the bookmarks.
--
Input: filepath (e.g. '/home/user/documents/mybookmarks.html')
Output:
- hash with the title and url of every bookmark
- nil if the input file is not valid
=end
  def self.parseFile(filepath)
    result = []

    File.open(filepath, "r").each_line do |line|
      result << {url: $1, title: $2} if line =~ /<dt>\s*<a href="(http[^"]+)"[^>]*>([^<]+)</i
    end

    return result
  end
end