#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: snapsbox
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"
    MONGOHQ_URL: "mongodb://snapsbox:34fmU8tV@alex.mongohq.com:10044/snapsbox"

staging:
  app: snapsbox-staging
  stack: cedar
  config: &default
    BUNDLE_WITHOUT: "development:test"
  addons:
    - pgbackups:auto-week
    - memcache:5mb
    - logging:basic
    - scheduler:standard

demo: 
  app: awesomeapp-demo
  config: *default
